
services:
  frontend:
    image: template_angular_21:latest
    container_name: myapp-frontend
    pull_policy: never
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_net
    restart: unless-stopped

  backend:
    image: backend_hexagonal_java:latest
    container_name: myapp-backend
    expose:
      - "9000"
    networks:
      - app_net
    restart: unless-stopped

networks:
  app_net:
    driver: bridge
